layout_spectrum: 0.8152465713089609
typography_spectrum: 0.16668256833577658
color:
  lightness: 0.5429475835271844
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  saturation: 0.6660801966171159
  brandStrength: 0.9771478565822881
  rhythmicContrast: 0.21500040575815826
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d8d6a5c-864b-40c0-bd0b-8eb3987d536f.png
name: Luke
url: 'http://lk.kbf.am'
navigation:
  - name: My Designer
    id: 1b3a31ee-18f4-4b63-841e-df0ceb76dae4
    type: content
  - name: About Me
    id: 70077636-65a2-4d18-819b-f01ddd22568a
    type: content
  - name: Sign Up
    url: 'http://eepurl.com/c0mRGj'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e9f452bc-6b5c-4db8-a163-8be8deb0b580.png
title: Luke Kosner
content: []
description: My space to be expressive.
purpose:
  - type: external
    url: 'http://db.kbf.am'
    label: Diane
  - type: external
    url: 'http://KosnerBurstein.com'
    label: KB
analytics:
  google: UA-104323546-4
