typography_spectrum: 0.16668256833577658
color:
  lightness: 0.5429475835271844
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  saturation: 0.6660801966171159
  brandStrength: 0.9771478565822881
  rhythmicContrast: 0.21500040575815826
github: true
layout_spectrum: 0.8152465713089609
analytics:
  google: UA-104323546-4
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b8299f37-6097-4a8d-977e-f465ce617e17.png
name: Luke
url: 'http://lk.kbf.am'
navigation:
  - name: My Designer
    id: 1b3a31ee-18f4-4b63-841e-df0ceb76dae4
    type: content
  - name: Sign Up
    url: 'http://eepurl.com/c0mRGj'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4233fca-a53a-4a3b-8b12-7efdd0f2168f.png
title: Luke Kosner
content: []
description: My space to be expressive.
purpose:
  - type: external
    url: 'http://db.kbf.am'
    label: Diane
  - type: external
    url: 'http://KosnerBurstein.com'
    label: KB
