layout_spectrum: 0.7848882656656944
typography_spectrum: 0.8794666452133235
color:
  lightness: 0.9820337611745747
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.08603780130818856
  brandStrength: 0.5591627012191359
  rhythmicContrast: 0.7335173052871176
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/741e2ab0-3d71-47e0-b35b-ccf5ebf148fb.png
name: Luke
url: 'http://lk.kbf.am'
navigation:
  - name: My Designer
    id: 1b3a31ee-18f4-4b63-841e-df0ceb76dae4
    type: content
  - name: About Me
    id: 70077636-65a2-4d18-819b-f01ddd22568a
    type: content
  - name: Sign Up
    url: 'http://eepurl.com/c0mRGj'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef7c4153-d3de-499f-81de-3dd19c094349.png
title: Luke Kosner
content: []
description: My space to be expressive.
purpose:
  - type: external
    url: 'http://KosnerBurstein.com'
    label: Kosner Burstein
  - type: external
    url: 'http://db.kbf.am'
    label: Diane
analytics:
  google: UA-104323546-4
