layout_spectrum: 0.9395245290206432
typography_spectrum: 0.662242927504058
color:
  lightness: 0.9865149602521727
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.08222392603155632
  brandStrength: 0.5587753120800573
  rhythmicContrast: 0.7313840901573179
github: true
logo: null
name: Luke
url: 'http://lk.kbf.am'
navigation:
  - name: My Designer
    id: 1b3a31ee-18f4-4b63-841e-df0ceb76dae4
    type: content
  - name: About Me
    id: 70077636-65a2-4d18-819b-f01ddd22568a
    type: content
  - name: Sign Up
    url: 'http://eepurl.com/c0mRGj'
    type: external
favicon: null
title: Luke Kosner
content: []
description: My space to be expressive.
purpose:
  - type: external
    url: 'http://KosnerBurstein.com'
    label: Kosner Burstein
  - type: external
    url: 'http://diane.kosnerburstein.com'
    label: Diane
